https://stackoverflow.com/questions/36967920/numpy-flatten-rgb-image-array
https://table19syd.australiaeast.cloudapp.azure.com:8000/user/table19syd/tree/OpenHack/hacker6/gear_images_out/output

In [14]:
import numpy as np
from sklearn.model_selection import train_test_split
import os

In [15]:
# !sudo pip install opencv-python

In [16]:
import cv2
# print(cv2.__version__)

In [17]:
# dirDict = { 
#     'tents_normalised': 0,
#     'gloves_normalised': 1,
#     'pulleys_normalised': 2,
#     'hardshell_jackets_normalised': 3,
#     'rope_normalised': 4,
#     'crampons_normalised': 5,
#     'boots_normalised': 6,
#     'insulated_jackets_normalised': 7,
#     'harnesses_normalised': 8,
#     'carabiners_normalised': 9,
#     'helmets_normalised': 10,
#     '.ipynb_checkpoints_normalised': None,
#     'axes_normalised': 11,
#     '.ipynb_checkpoints': None
# }
# y_data = []
# for root, dirs, files in os.walk("./gear_images_out/output"):
#     for name in dirs:
# #         print(dirDict[name])
#         dirInt = dirDict[name]
#         if dirInt != None:
# #             print(dirInt)
#             y_data.append(dirInt)
# y_data = np.array(y_data)
# print(y_data)

In [18]:
# import numpy as np
# from matplotlib import pyplot as plt
# from PIL import Image
# import cv2


# x_data = []
# y_data=[]
# #flatten data

# for image in os.listdir("./gear_images_out/output"):
#     pixels =  np.array(cv2.imread(path)
#     pixels = pixels.flatten()
                        
# for imagePath in os.walk("./gear_images_out/output"):
#         x_data.append(getpixels(imagePath))
#         print(x_data)


In [19]:
# #name = "./gear_images/output/axes_normalized"
# #print(os.path.basename(name))

# y_data = []

# for root, dirs, files in os.walk("./gear_images_out/output"):
#     for name in dirs:
#                 temp_data = os.path.join(root, name)
# #                 print (temp_data)
#                 if temp_data.endswith("normalised"):
#                     for image in os.listdir(temp_data):
#                         y_data.append(os.path.basename(temp_data))
# # print(y_data)

# # y_data2 = map(lambda x: dirDict[x], y_data)
# # print(np.array(y_data2))

# y_data_int = []
# for i in y_data:
# #     print(dirDict[i])
#     y_data_int.append(dirDict[i])
# # print(y_data_int)
# y_data = np.array(y_data_int)
# print(y_data)
# y_data.shape

In [20]:
# for image in os.listdir("./gear_images_out/output"):
#     pixels =  np.array(cv2.imread(path)
#     pixels = pixels.flatten()
                        
# for imagePath in os.walk("./gear_images_out/output"):
#         x_data.append(getpixels(imagePath))
#         print(x_data)

In [21]:
# # https://stackoverflow.com/questions/7762948/how-to-convert-an-rgb-image-to-numpy-array# 
    
# dirDict = { 
#     'tents_normalised': 0,
#     'gloves_normalised': 1,
#     'pulleys_normalised': 2,
#     'hardshell_jackets_normalised': 3,
#     'rope_normalised': 4,
#     'crampons_normalised': 5,
#     'boots_normalised': 6,
#     'insulated_jackets_normalised': 7,
#     'harnesses_normalised': 8,
#     'carabiners_normalised': 9,
#     'helmets_normalised': 10,
#     '.ipynb_checkpoints_normalised': None,
#     'axes_normalised': 11,
#     '.ipynb_checkpoints': None
# }
# x_data = []

# for root, dirs, files in os.walk("./gear_images_out/output"):
#     for name in dirs:
# #         print(dirDict[name])
#         dirInt = dirDict[name]
#         if dirInt != None:
#             x_dir = os.path.join(root, name)
# #             print(dirInt)
# #             print(os.listdir(y_data))
#             for f in os.listdir(x_dir):
# #                 print(f)
# #                 print(dirInt)
#                 im = cv2.imread(os.path.join(x_dir, f))
# #                 print(im.shape)
# #
#                 im = im.flatten()
#                 print(im)
                

# # print(np.array(x_data).flatten())
# x_data = np.array(im)

# print(x_data)

In [22]:
# https://stackoverflow.com/questions/7762948/how-to-convert-an-rgb-image-to-numpy-array# 
    
dirDict = { 
    'tents_normalised': 0,
    'gloves_normalised': 1,
    'pulleys_normalised': 2,
    'hardshell_jackets_normalised': 3,
    'rope_normalised': 4,
    'crampons_normalised': 5,
    'boots_normalised': 6,
    'insulated_jackets_normalised': 7,
    'harnesses_normalised': 8,
    'carabiners_normalised': 9,
    'helmets_normalised': 10,
    '.ipynb_checkpoints_normalised': None,
    'axes_normalised': 11,
    '.ipynb_checkpoints': None
}
x_data = []
y_data = []
for root, dirs, files in os.walk("./gear_images_out/output"):
    for name in dirs:
#         print(dirDict[name])
        dirInt = dirDict[name]
        if dirInt != None:
            x_dir = os.path.join(root, name)
#             print(dirInt)
#             print(os.listdir(y_data))
            for f in os.listdir(x_dir):
#                 print(f)
#                 print(dirInt)
                y_data.append(dirInt)
                im = cv2.imread(os.path.join(x_dir, f))
#                 print(im.shape)
#                 print(im)
                im = im.flatten()
#                 x_data.append(im.tolist())
                x_data.append(im)

# print(np.array(x_data).flatten())


# x_data = np.array(x_data).flatten()

print(np.array(x_data).shape) 
print(np.array(y_data).shape) 
print(x_data[5])


(2122, 49152)
(2122,)
[255 255 255 ... 255 255 255]


In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import numpy.random as nr
import math
from sklearn.preprocessing import StandardScaler
import sklearn.model_selection as ms
from sklearn import linear_model
import sklearn.metrics as sklm

%matplotlib inline

Labels = np.array(y_data)
Features = np.array(x_data)

## Randomly sample cases to create independent training and test datanr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 531)
X_train = Features[indx[0],]
y_train = np.ravel(Labels[indx[0]])
X_test = Features[indx[1],]
y_test = np.ravel(Labels[indx[1]])


In [24]:
scaler = StandardScaler()
print(scaler.fit(X_train))
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train[5]

/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)


/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([0.15733667, 0.15672293, 0.15789165, ..., 0.16145502, 0.15975578,
       0.16097559])

In [25]:
#logistic_mod = linear_model.LogisticRegression() 
#logistic_mod.fit(X_train, y_train)
from sklearn.ensemble import RandomForestClassifier
forest_mod = RandomForestClassifier(n_estimators = 1000, random_state = 42)
forest_mod.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [26]:
probabilities = forest_mod.predict_proba(X_test)
print(probabilities[:15,])

def score_model(probs):
    scores = []
    for x in probs:
        scores.append(np.argmax(x))
    return scores

scores = score_model(probabilities)
print(scores[:15])
print(y_test[:15])

[[0.006 0.89  0.003 0.006 0.039 0.005 0.002 0.034 0.008 0.    0.007 0.   ]
 [0.    0.032 0.001 0.792 0.012 0.    0.004 0.155 0.001 0.001 0.002 0.   ]
 [0.002 0.069 0.054 0.048 0.029 0.008 0.006 0.023 0.011 0.013 0.726 0.011]
 [0.    0.017 0.007 0.836 0.002 0.    0.001 0.136 0.001 0.    0.    0.   ]
 [0.003 0.056 0.049 0.176 0.109 0.003 0.01  0.535 0.02  0.008 0.031 0.   ]
 [0.001 0.047 0.027 0.008 0.034 0.008 0.    0.015 0.03  0.012 0.818 0.   ]
 [0.005 0.012 0.004 0.    0.028 0.051 0.003 0.    0.006 0.018 0.003 0.87 ]
 [0.    0.005 0.022 0.492 0.    0.    0.    0.481 0.    0.    0.    0.   ]
 [0.    0.051 0.011 0.008 0.04  0.024 0.031 0.008 0.732 0.051 0.025 0.019]
 [0.001 0.005 0.    0.001 0.02  0.008 0.947 0.002 0.009 0.003 0.002 0.002]
 [0.001 0.006 0.006 0.829 0.003 0.    0.007 0.147 0.    0.    0.001 0.   ]
 [0.    0.967 0.003 0.003 0.01  0.002 0.    0.007 0.007 0.    0.001 0.   ]
 [0.    0.004 0.006 0.735 0.    0.    0.001 0.253 0.001 0.    0.    0.   ]
 [0.    0.001 0.001 0.002

In [27]:
from sklearn import metrics
expected = y_test
predicted  = scores
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        32
          1       0.94      0.94      0.94        49
          2       1.00      0.60      0.75        10
          3       0.82      0.90      0.86       116
          4       1.00      0.88      0.94        60
          5       0.76      0.96      0.85        27
          6       0.93      0.96      0.94        26
          7       0.73      0.66      0.69        56
          8       0.98      1.00      0.99        45
          9       0.98      0.95      0.97        65
         10       0.95      0.90      0.92        20
         11       0.92      0.88      0.90        25

avg / total       0.90      0.90      0.90       531

[[ 32   0   0   0   0   0   0   0   0   0   0   0]
 [  0  46   0   2   0   0   0   1   0   0   0   0]
 [  0   1   6   1   0   0   1   0   0   0   1   0]
 [  0   0   0 104   0   0   0  12   0   0   0   0]
 [  0   0   0   0  53   5   1   1   0   0   0   0]
